AIUCafeteria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include("dashboard.urls")),
    path('',include("UserPage.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

UserPage/urls.py
from django.urls import path
from . import views

app_name = 'Userpage'
urlpatterns = [
    path('', views.TodayMenu.as_view(), name='TodayMenu'),
    path('Food-List', views.ViewallFood.as_view(), name='ViewallFood'),

    path('vote',views.processVote, name='vote')
   
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.Dashboard.as_view(), name='index'),
    # path('addFood/', views.AddFood.as_view(), name='addFood'),
    path('viewallfood/', views.ViewAllFood.as_view(), name='viewallfood'),
    path('editfood/<str:pk>', views.EditFood.as_view(), name='editfood'),
    path('delete/<str:pk>', views.DeleteFood.as_view(), name='delete'),
    path('post/', views.CreatePostView.as_view(), name='add_post'),
    path('multidel/', views.AllFoodList.as_view(), name='delete_multi')
]

dashboard/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Food(models.Model):

    DAYS = (
        ('Sunday', 'Sunday'),
        ('Monday', 'Monday'),
        ('Tuesday', 'Tuesday'),
        ('Wednesday', 'Wednesday'),
        ('Thursday', 'Thursday'),
        ('Friday', 'Friday'),
        ('Saturday', 'Saturday'),
    )

    foodId = models.AutoField(primary_key=True)
    foodImage = models.ImageField(upload_to='images/', null=True, blank=True)
    foodName = models.CharField(max_length=100)
    foodAddDate = models.DateTimeField(null=True, blank=True, auto_now=True)
    foodPrice = models.IntegerField(default=0)
    foodAvailableDay = models.CharField(max_length=20, choices=DAYS, null=True, blank=True)

    def __str__(self):
        return f"{self.foodId}"






class Vote(models.Model):
    voteId = models.AutoField(primary_key=True)
    foodId = models.OneToOneField(Food, on_delete=models.CASCADE)
    upVote = models.IntegerField(default=0)
    downVote = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.foodId}"

    @receiver(post_save, sender=Food)
    def setVoter(sender, instance, created, **kwargs):
        if created:
            
            # vote = Vote.objects.create(food=kwargs['instance'])
            print("YES?!")

            

dashboard/forms.py
from .models import Food, Vote
from django import forms

class addFood(forms.ModelForm):
    class Meta:
        model = Food
        fields = ['foodImage', 
                    'foodName', 
                    'foodPrice',
                    ]

dashboard/views.py
from django.core.checks import messages
from django.http import request
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from .models import Food, Vote
from .forms import addFood
import os
from django.contrib import messages
from datetime import date
import calendar

class Dashboard(generic.ListView):
    model = Food
    template_name = 'dashboard/index.html'
    # context_object_name = 'foods'

    def get(self, request, *args, **kwargs):

        
        my_date = date.today()
        today = calendar.day_name[my_date.weekday()] 
        today_listing = Food.objects.all().filter(foodAvailableDay = today)
        today_listing_count = today_listing.count()

        vote = Vote.objects.all()


        foods = Food.objects.all()
        feature = foods.order_by('-foodAddDate')[:10]
        count = foods.count()

        # for food in foods:
        #     id = food.foodId
        #     print("Food ID")
        #     print(id)

        #     v = Vote.objects.get(foodId=id)
        #     print("Vote")
        #     print(v)
            




        context = {
            'foods':feature,
            'count':count,
            'vote':vote,
            'today_listing_count': today_listing_count
        }
        return render(request, self.template_name, context)

class ViewAllFood(generic.ListView):
    model = Food
    template_name = 'dashboard/allFood.html'
    context_object_name = 'foods'

    def get_queryset(self):
        return Food.objects.all().order_by('-foodAddDate')

class AllFoodList(generic.View):
    def get(self, request):
        allFood = Food.objects.all()
        context = {
            'foods':allFood
        }

        return render(request, 'dashboard/allFoodList.html', context)

    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            food_id = request.POST.getlist('id[]')
            for id in food_id:
                print(id)
                food = Food.objects.get(pk=id)
                food.delete()
            return redirect('dashboard:delete_multi')



# class AddFood(generic.CreateView):
#     model = Food
#     template_name = 'dashboard/index.html'
#     form_class = addFood
#     success_url = '/dashboard/'

class CreatePostView(generic.CreateView):
    model = Food
    form_class = addFood
    template_name = 'dashboard/post.html'
    success_url = reverse_lazy('dashboard:viewallfood')

    def form_valid(self,form):
        self.instance =form.save(commit=False)
 
        foodName = form.cleaned_data['foodName']
        foodPrice = form.cleaned_data['foodPrice']
        foodImage = form.cleaned_data['foodImage']
        food= Food(foodImage=foodImage,foodName=foodName, foodPrice=foodPrice, foodAvailableDay='Wednesday' )
        food.save()
       
        votes= Vote(foodId=food, upVote=0, downVote=0 )
        votes.save()

        return redirect('dashboard:viewallfood')


    # def post(self, request, *args, **kwargs):
    #     messages.success(request, "Congraadulation, New Food Added into Menu")
    #     return redirect('/dashboard/')


class EditFood(generic.UpdateView):
    model = Food
    fields = ['foodImage', 'foodName', 'foodPrice', 'foodAvailableDay']
    template_name = 'dashboard/editFood.html'
    success_url = reverse_lazy('dashboard:viewallfood')

    # def post(self, request, *args, **kwargs):
    #     form = addFood(request.POST)
    #     if form.is_valid():
    #         super()

    #     messages.success(request, "Yayyy!!")
    #     return super().get(request, *args, **kwargs)

class DeleteFood(generic.DeleteView):
    model = Food
    success_url = reverse_lazy('dashboard:viewallfood')

dashboard/templates/dashboard/add.html
<h1>Hello</h1>
    <form action="{% url 'dashboard:addFood' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}  
        <input type="submit">
    </form>

dashboard/templates/dashboard/allFood.html
{% extends "dashboard/base.html" %}
{% load static %}

{% block main %}


<p></p>


<div class="container">
  <form class="d-flex">
    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success" type="submit">Search</button>
  </form>

  <p>
    <br>
  </p>

    <div class="row">
        {% for food in foods %}
        <div class="col-sm-3">
            <div class="card" style="width: 100%; margin-bottom: 20px;">

                {% if food.foodImage %}
                <img src="{{ food.foodImage.url }}" alt="">
                {% else %}
                <img src="{% static 'dashboard/img/food_profile.png' %}" alt="" style="width: 100%;">
                {% endif %}
              
                <div class="card-body">
                  <h5 class="card-title">{{ food.foodName }}</h5>
                  <p class="card-text">{{ food.foodPrice }} THB</p>
                  <a class="btn btn-sm btn-info" href="{% url 'dashboard:editfood' food.foodId %}">Update</a>
                  <a class="btn btn-sm btn-danger" href="{% url 'dashboard:delete' food.foodId %}">Delete</a>

                </div>
              </div>
        </div>
        {% empty %}
        <p>No Food added yet</p>
        {% endfor %}
      </div>
  </div>



{% endblock %}

dashboard/templates/dashboard/allFoodList.html
{% extends "dashboard/base.html" %}
{% load static %}

{% block main %}

    <!-- <div class="container">
        <div class="row">
        <div class="card card-body">
            <table class="table table-sm">
                <thead>
                    <th></th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Date Added</th>
                </thead>
                <tbody>
                    {% csrf_token %}
                    {% for food in foods %}
                    <tr id="{{food.foodId}}">
                        <td><input type="checkbox" name="food_id[]" value="{{food.foodId}}" id="delete_food"></td>
                        <td>{{ food.foodName }}</td>
                        <td>{{ food.foodPrice }}</td>
                        <td>{{ food.foodAddDate }}</td>
                    </tr>
                    {% endfor %}
                    
                </tbody>
            </table>
        </div>
        </div>
        <div>
            <button type="submit" id="delete_btn" class="btn_delete">Delete</button>
        </div>
    </div> -->

    <!-- TABLE -->
    
    <p>
        <br>
        <br>
    </p>
    <div class="container">
        <h1>Select To Delete</h1>
        <div class="row">
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col">Name</th>
                <th scope="col">Price</th>
                <th scope="col">Up Vote</th>
                <th scope="col">Date Added</th>
            </tr>
            </thead>
            <tbody>
                {% csrf_token %}
                {% for food in foods %}
                <tr id="{{food.foodId}}">


                    <td><input type="checkbox" name="food_id[]" value="{{food.foodId}}" id="delete_food" ></td>


                    <!-- <input type="checkbox" class="btn-check" id="btncheck1" autocomplete="off"> -->
                    


                    <td>{{ food.foodName }}</td>
                    <td>{{ food.foodPrice }}</td>
                    <td> UpVote </td>
                    <td>{{ food.foodAddDate }}</td>
                </tr>
                {% endfor %}
                <tr><button type="submit" id="delete_btn" class="btn btn-sm btn-danger">Delete</button></tr>
            </tbody>
        </table>
        <div>
            
        </div>
    </div>
</div>
    <!-- END TABLE -->



    <script src="https://code.jquery.com/jquery-3.6.0.js" 
    integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" 
    crossorigin="anonymous"></script>
    <script>
        $(document).ready(function() {
            $('#delete_btn').click(function() {
                if(confirm("Are You Sure?")) {
                    var id =[];
                    var csrf='{{ csrf_token }}';
                    $(':checkbox:checked').each(function(i){
                        id[i] = $(this).val()
                    })
                    if(id.length===0) {
                        alert("Please select")
                    } else {
                        console.log(id);
                        console.log(csrf);
                        $.ajax({
                            url: ".",
                            method: "POST",
                            data: {
                                id,
                                csrfmiddlewaretoken:csrf
                            },
                            success:function(response) {
                                for(var i=0; i < id.length; i++) {
                                    $('tr#' + id[i] + '').css('background-color: #111');
                                    $('tr#' + id[i] + '').fadeOut('fast');
                                }
                            }
                        })
                    }
                }
            })
        })
    </script>

{% endblock %}
    

dashboard/templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'dashboard/css/main.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light ">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'dashboard:index' %}">HOME</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              

          </div>
        </div>
      </nav>
    {% block main %}
    {% endblock %}
</body>
</html>

dashboard/templates/dashboard/editFood.html
{% extends "dashboard/base.html" %}
{% load static %}

{% block main %}

<form class="edit-note" method="post">
    
    {% csrf_token %}
    <h1>{{ form.as_p }}</h1>

    <div class="formbutton">
        <a href="{% url 'dashboard:index' %}"><button type="button">Back</button><br></a>
        <button  type="submit">Save</button><br>
    </div>  
    
</form>

{% endblock %}

dashboard/templates/dashboard/food_confirm_delete.html
{% extends "dashboard/base.html" %}
{% load static %}

{% block main %}

    <form class="confirm-delete"method="post">
        <h1 class="addNoteHeader">Delete Note</h1>
        {% csrf_token %} 
        <hr>
        <button class="two" type="submit">Yes</button>
        <a href="{% url 'dashboard:index' %}"><button  class="one" type="button">No</button><br></a>
    </form> 

{% endblock %}

dashboard/templates/dashboard/index.html
{% extends "dashboard/base.html" %}
{% load static %}




{% block main %}
{% if messages %}
    {% for message in messages%}
     {{ message }}
    {% endfor %}
{% endif %}
<br>
<div class="container">

<div class="row">
	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="total-orders">
			  	<div class="card-header">
			  		<h5 class="card-title">Total Menu</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{ today_listing_count }} | {{ count }}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-delivered">
			  	<div class="card-header">
			  		<h5 class="card-title">Add Menu</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title"><a  href="{% url 'dashboard:add_post' %}"><img src="{% static 'dashboard/img/add.png' %}" alt="" width="35px"></a></h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-pending">
			  	<div class="card-header">
			  		<h5 class="card-title">Delete Menu</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title"><a  href="{% url 'dashboard:delete_multi' %}"><img src="{% static 'dashboard/img/delete.png' %}" alt="" width="35px"></a></h3>
			  	</div>
			</div>
		</div>
	</div>
</div>
</div>
<br>

<div class="container">
    <div class="row">
        <div class="col-md-5">

            <!-- CLOCK -->

            <div id="clock">
                <p>
                    <br>
                    <br>
                    <br>
                </p>

                <div id="time">

                    <div>
                       <span id="hour">00</span><span>Hour</span>
                    </div>

                    <div>
                       <span id="minutes">00</span><span>Minutes</span>
                    </div>

                    <div>
                       <span id="seconds">00</span><span>Seconds</span>
                    </div>

                </div>
                <p>
                    <br>
                </p>
                <div id="openClose">
                    CLOSE
                </div>
            </div>

        </div>

        <div class="col-md-7">

        <hr>
        <div class="card card-body">
            
            <table class="table table-sm">
                <tr>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Upvote</th>
                    <th></th>
                    <th></th>
                </tr>

                    {% for food in foods %}
                    <tr>
                        <td>{{ food.foodName }}</td>
                        <td>{{ food.foodPrice }} THB</td>
                        <td>{{ food.vote }}</td>
                        <td><a class="btn btn-sm btn-info" href="{% url 'dashboard:editfood' food.foodId %}">Update</a></td>
                        <td><a class="btn btn-sm btn-danger" href="{% url 'dashboard:delete' food.foodId %}">Delete</a></td>

                    </tr>

                    {% empty %}
                    <p>No Food added yet</p>
                    {% endfor %}
                    <div></div>
                    
                    <tr>
                        <td ><a href="{% url 'dashboard:viewallfood' %}" class="btn btn-primary">View All</a></td>
                    </tr>
            </table>
            </div>
        </div>
    </div>

    </div>
</div>

<script type="text/javascript">

function clock() {
    var hours = document.getElementById('hour');
    var minutes = document.getElementById('minutes');
    var seconds = document.getElementById('seconds');
    var checkOpen = document.getElementById('openClose');

    var h = new Date().getHours();
    var m = new Date().getMinutes();
    var s = new Date().getSeconds();

    h = (h < 10) ? "0" + h : h
    m = (m < 10) ? "0" + m : m
    s = (s < 10) ? "0" + s : s

    hours.innerHTML = h;
    minutes.innerHTML = m;
    seconds.innerHTML = s;

    if (s < 40) {
        checkOpen.innerHTML = 'OPEN'
        checkOpen.style.background = '#0fb900'
    } else {
        checkOpen.innerHTML = 'CLOSE'
        checkOpen.style.background = '#ce0606e7'
    }
}

var interval = setInterval(clock, 1000);
</script>

{% endblock %}

dashboard/templates/dashboard/post.html
{% extends "dashboard/base.html" %}
{% load static %}

{% block main %}


<form class="container" method="post" enctype="multipart/form-data">
    <br>
    <br>
    <br>

    <h1>Add Food To Menu</h1>
    <p></p>
  {% csrf_token %}
    <div class="row">


        <div class="mb-3">
            <label for="foodImage" class="form-label">Image: <span class="badge bg-success">Important</span></label>
            <tr></tr><input  type="file" name="foodImage" class="form-control"></tr>
        </div>

        <div class="mb-3">
            <label for="foodName" class="form-label">Name: <span class="badge bg-success">Important</span></label>
            <tr><input type="text" name="foodName" class="form-control" id="food-name"></tr>
        </div>

        <div class="mb-3">
            <label for="foodPrice" class="form-label">Price: <span class="badge bg-success">Important</span></label>
            <tr><input id="food-price" type="number" name="foodPrice" class="form-control"></tr>
        </div>

        <div class="mb-2">
            <label for="foodAvailableDay" class="form-label">Available Day: <span class="badge bg-warning text-dark">Can pick more than one.</span></label>
        </div>

        <div class="btn-group" role="group" aria-label="Basic checkbox toggle button group">
            <input type="checkbox" class="btn-check" name="foodAvailableDay"  value="Sunday" id="Sunday" autocomplete="off">
            <label class="btn btn-outline-primary" for="Sunday">Sunday</label>

            <input type="checkbox" class="btn-check" name="foodAvailableDay"  value="Monday" id="Monday" autocomplete="off">
            <label class="btn btn-outline-primary" for="Monday">Monday</label>

            <input type="checkbox" class="btn-check" name="foodAvailableDay"  value="Tursday" id="Tursday" autocomplete="off">
            <label class="btn btn-outline-primary" for="Tursday">Tursday</label>

            <input type="checkbox" class="btn-check" name="foodAvailableDay"  value="Wenesday" id="Wenesday" autocomplete="off">
            <label class="btn btn-outline-primary" for="Wenesday">Wenesday</label>

            <input type="checkbox" class="btn-check" name="foodAvailableDay"  value="Thursday" id="Thursday" autocomplete="off">
            <label class="btn btn-outline-primary" for="Thursday">Thursday</label>

            <input type="checkbox" class="btn-check" name="foodAvailableDay"  value="Friday" id="Friday" autocomplete="off">
            <label class="btn btn-outline-primary" for="Friday">Friday</label>

            <input type="checkbox" class="btn-check" name="foodAvailableDay"  value="Saturday" id="Saturday" autocomplete="off">
            <label class="btn btn-outline-primary" for="Saturday">Saturday</label>

        </div>
        <p>
            <br>
        </p>
        <tr><button type="submit" class="btn btn-primary" id="create-food" >Add The Food To The Menu</button></tr>
        <p></p>


    </div>

</form>

{% endblock %}

dashboard/templates/dashboard/status.html
<br>
<div class="container">

<div class="row">
	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="total-orders">
			  	<div class="card-header">
			  		<h5 class="card-title">Total Menu</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">#</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-delivered">
			  	<div class="card-header">
			  		<h5 class="card-title">Today Listing</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">#</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-pending">
			  	<div class="card-header">
			  		<h5 class="card-title">Up Vote</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">#</h3>
			  	</div>
			</div>
		</div>
	</div>
</div>
</div>