AIUCafeteria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include("dashboard.urls")),
    path('',include("UserPage.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

UserPage/urls.py
from django.urls import path
from . import views

app_name = 'Userpage'
urlpatterns = [
    path('', views.TodayMenu.as_view(), name='TodayMenu'),
    path('Food-List', views.ViewallFood.as_view(), name='ViewallFood'),

    path('vote',views.processVote, name='vote')
   
]

UserPage/models.py
from django.db import models

# Create your models here.

UserPage/views.py
from django.db.models.fields.related import ForeignKey
from django.shortcuts import redirect, render, get_object_or_404
from django.views import generic
from django.views.generic.list import ListView
from dashboard.models import Food, Vote
from django.http import Http404, JsonResponse
from django.db.models import F,Q
from datetime import date
import calendar
from itertools import chain
from operator import attrgetter

class ViewallFood(generic.ListView):
    model = Vote
    template_name = 'UserPage/ViewallFood.html'
    context_object_name = 'votes'

    def get_queryset(self):
        return Vote.objects.all()[:10]
        

class TodayMenu(generic.ListView):
    model = Vote
    template_name = 'UserPage/UserDashboard.html'
    context_object_name = 'votes'

    def get_queryset(self):
      
        # votes=  Vote.objects.all()

        # allFoods = sorted(chain(foods, votes), key=attrgetter('foodId'))
        # return allFoods

        my_date = date.today()
        today = calendar.day_name[my_date.weekday()] 
        print(today)
        return Food.objects.all().filter(foodAvailableDay = today )
        
        


def processVote( request):
    print("hello")
    print(request.POST)
    if request.is_ajax and request.method =="POST":
        type = request.POST.get('type', 0)
        if type and type=='upVote' or type=='downVote' :
            food= Food.objects.get(pk=request.POST['foodId'])
            if Vote.objects.filter(foodId=request.POST['foodId']).exists():
                if type=='upVote':
                    voteItem = Vote.objects.get(foodId=Food.objects.get(pk=request.POST['foodId']))
                    voteItem.upVote= F('upVote') + 1
                    voteItem.save()
                elif type=='downVote':
                    voteItem = Vote.objects.get(foodId=Food.objects.get(pk=request.POST['foodId']))
                    voteItem.downVote= F('downVote') + 1
                    voteItem.save() 
            else:
                if type=='upVote':
                    vote = Vote(foodId=food, upVote=1, downVote=0 )
                    vote.save()
                elif type=='downVote': 
                    vote = Vote(foodId=food, upVote=0, downVote=1 )
                    vote.save()

    return redirect('Userpage:TodayMenu')


                 
                    




        

UserPage/templates/UserPage/UserDashboard.html
{% extends "UserPage/base.html" %}
{% load static %}
{% block main %}

<h1>Todays Menu </h1>
<section id="foodSection">  
  {% for vote in votes %}
 
  <div class="foodItem">
    <h2>{{vote.foodName}}</h2>
    <div class="foodPic">
       {% if vote.foodImage %}
            <img src="{{ vote.foodImage.url }}" alt="">
            {% else %}
            <img src="{% static 'dashboard/img/food_profile.png' %}" alt="" >
            {% endif %} 
        
    </div>
    <div class="votes">
        <a class="voteOption1" type="button" id="upVote" value="{{vote.foodId}}">  <i class="fa fa-thumbs-up">{{ vote.upVote }}</i>0</a>
      <a class="voteOption2" type="button" id="downVote" value="{{vote.foodId}}"> <i class="fa fa-thumbs-down">{{ vote.downVote }}</i>0</a>
      <p class="price">{{vote.foodPrice}} baht</p> 
    </div>  
  
  </div>
  {% endfor %}


    </section>
<button><a class="nav" href="{% url 'Userpage:ViewallFood' %}" > View Food List </a></button>
   
{% endblock main %}

{% block js %}


<script>
  

const sendData = (data, refresh) => {
    $.ajax({
     type: 'POST',
      url: "{% url 'Userpage:vote' %}",
      data: data,
    success: function (response) {
    },
    error: function(response) {
    },
    complete: function() {
     if (refresh) {
      setTimeout(() => {location.reload()}, 1500);
      }
    }})}

    
    $(document).on('click', '[id^=upVote]', function() {
      const data = {
        'type': "upVote",
        'foodId': $(this).attr('value'),
        'csrfmiddlewaretoken': "{{ csrf_token}}"
        };
   
    sendData(data, true);
    })

    $(document).on('click', '[id^=downVote]', function() {
      const data = {
        'type': "downVote",
        'foodId': $(this).attr('value'),
        'csrfmiddlewaretoken': "{{ csrf_token}}"
        };
   
    sendData(data, true);
    })
  
</script>


{% endblock js %}


   

UserPage/templates/UserPage/ViewallFood.html
{% extends "UserPage/base.html" %}
{% load static %}
{% block main %}

<h1>Food List</h1>
<section id="foodSection">
  {% for vote in votes %}
  <div class="foodItem">
    <h2>{{vote.foodId.foodName}} </h2>
    <div class="foodPic">
       {% if vote.foodId.foodImage %}
            <img src="{{ vote.foodId.foodImage.url }}" alt="">
            {% else %}
            <img src="{% static 'dashboard/img/food_profile.png' %}" alt="" >
            {% endif %} 
        
    </div>
    <div class="votes">
        <a class="voteOption1" type="button" id="upVote" value="{{vote.foodId}}">  <i class="fa fa-thumbs-up">{{ vote.upVote }}</i></a>
      <a class="voteOption2" type="button" id="downVote" value="{{vote.foodId}}"> <i class="fa fa-thumbs-down">{{ vote.downVote }}</i></a>
     <p class="price">{{vote.foodId.foodPrice}} baht</p> 
    </div>   
  </div>
  {% endfor %}
      

    </section>
   <button> <a class="nav" href="{% url 'Userpage:TodayMenu' %}"> View Todays Menu</a></button>
   
{% endblock main %}

{% block js %}


<script>
  

const sendData = (data, refresh) => {
    $.ajax({
     type: 'POST',
      url: "{% url 'Userpage:vote' %}",
      data: data,
    success: function (response) {
    },
    error: function(response) {
    },
    complete: function() {
     if (refresh) {
      setTimeout(() => {location.reload()}, 1500);
      }
    }})}

    
    $(document).on('click', '[id^=upVote]', function() {
      console.log($(this).attr('value'))
      const data = {
        'type': "upVote",
        'foodId': $(this).attr('value'),
        'csrfmiddlewaretoken': "{{ csrf_token}}"
        };
   
    sendData(data, true);
    })

    $(document).on('click', '[id^=downVote]', function() {
      const data = {
        'type': "downVote",
        'foodId': $(this).attr('value'),
        'csrfmiddlewaretoken': "{{ csrf_token}}"
        };
   
    sendData(data, true);
    })
  
</script>


{% endblock js %}


   

UserPage/templates/UserPage/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!--    <meta http-equiv="refresh" content="3;">  -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'UserPage/css/main.css' %}">
    <title>FVS</title>
</head>
<body class="container">
    <header >
        <h1>Cafeteria Food Viewing System</h1>
          <p>By Group 4</p>
    </header> 
    {% block main %}

    {% endblock main %}

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script></script>

    {% block js %}

    {% endblock js %}

</body>
</html>